services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    depends_on: tailscale
    user: 1000:1000 # owner of your music library
    restart: unless-stopped
    network_mode: service:tailscale
    volumes:
      - ./navidrome:/data:Z
      - /path/to/your/music/folder:/music:ro
  tailscale:
    image:
      image: tailscale/tailscale:latest
      container_name: navidrome-ts
      restart: unless-stopped
    environment:
      TS_AUTHKEY: "YOUR_AUTH_KEY"
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_HOSTNAME: "HOSTNAME_IN_TAILNET"
      TS_USERSPACE: false
    cap_add:
      - net_admin
      - sys_module
    volumes:
      - ./vnavidrome-ts:/var/lib/tailscale:Z
      - /dev/net/tun:/dev/net/tun